//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoArchive.App.Model
{
    using System;
    using System.Collections.Generic;
    using System.Security.Cryptography;
    using System.Text;

    public partial class User
    {
        public int id { get; set; }
        public string firstName { get; set; }
        public string secondName { get; set; }
        public string login { get; set; }
        public string password { get; set; }

        public User() { }

        public User(string firstName, string secondName, string login, string password)
        {
            this.firstName = firstName;
            this.secondName = secondName;
            this.login = login;
            this.password = password;
        }

        public static string getHash(string password)
        {
            if (String.IsNullOrEmpty(password))
            {
                return "Error";
            }
            else
            {
                var md5 = MD5.Create();
                var hash = md5.ComputeHash(Encoding.UTF8.GetBytes(password));
                return Convert.ToBase64String(hash);
            }
        }
    }
}
